# Site
name: "o som do silêncio."
title: "o som do silêncio."
url: "https://osomdosilencio.com.br"
description: "Tentando transparecer sentimento e vivências através da música."
locale: pt_BR
image: /assets/images/logo.png
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ""   
google_analytics: ''
disqus: ''
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  igor:
    name: Igor Henrique Constant
    display_name: Igor Henrique Constant
    description: ''
    web: ''
    twitter: ''
    avatar: ''
 
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
